# __init__.py

from .clip_min_ranker import NODE_CLASS_MAPPINGS as CLIP_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLIP_DISPLAY_MAPPINGS
from .custom_save_image import NODE_CLASS_MAPPINGS as SAVE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAVE_DISPLAY_MAPPINGS


NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(CLIP_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SAVE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(CLIP_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SAVE_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
